apiVersion: v1
kind: Secret
metadata:
  name: function-config
  namespace: crossplane-system
type: Opaque
stringData:
  config.yaml: |
    apiVersion: function-claude-status-transformer.fn.crossplane.io/v1alpha1
    kind: FunctionConfig
    metadata:
      name: function-config
      namespace: crossplane-system
    spec:
      credentials:
        source: WebIdentity
        webIdentity:
          roleARN: arn:aws:iam::123456789012:role/providerexamplerole
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: transform-status-with-claude
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: App
  mode: Pipeline
  pipeline:
  - step: make-claude-do-it
    functionRef:
      name: function-claude-status-transformer
    input:
      apiVersion: function-claude-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      additionalContext: ""
      aws:
        bedrock: {}
    credentials:
    - name: function-config
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: function-config