apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: transform-status-with-claude
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: App
  mode: Pipeline
  pipeline:
  - step: make-claude-do-it
    functionRef:
      name: function-claude-status-transformer
    input:
      apiVersion: function-claude-status-transformer.fn.crossplane.io/v1beta1
      kind: StatusTransformation
      additionalContext: ""
      aws:
        functionConfigRef:
          name: example-aws-creds
        bedrock: {}
    credentials:
    - name: example-aws-creds
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: example-aws-creds