//go:build !ignore_autogenerated

/*
Copyright 2025 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSFunctionConfig) DeepCopyInto(out *AWSFunctionConfig) {
	*out = *in
	in.Credentials.DeepCopyInto(&out.Credentials)
	if in.AssumeRoleChain != nil {
		in, out := &in.AssumeRoleChain, &out.AssumeRoleChain
		*out = make([]AssumeRoleOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(EndpointConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSFunctionConfig.
func (in *AWSFunctionConfig) DeepCopy() *AWSFunctionConfig {
	if in == nil {
		return nil
	}
	out := new(AWSFunctionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssumeRoleOptions) DeepCopyInto(out *AssumeRoleOptions) {
	*out = *in
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]Tag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransitiveTagKeys != nil {
		in, out := &in.TransitiveTagKeys, &out.TransitiveTagKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssumeRoleOptions.
func (in *AssumeRoleOptions) DeepCopy() *AssumeRoleOptions {
	if in == nil {
		return nil
	}
	out := new(AssumeRoleOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssumeRoleWithWebIdentityOptions) DeepCopyInto(out *AssumeRoleWithWebIdentityOptions) {
	*out = *in
	if in.RoleARN != nil {
		in, out := &in.RoleARN, &out.RoleARN
		*out = new(string)
		**out = **in
	}
	if in.TokenConfig != nil {
		in, out := &in.TokenConfig, &out.TokenConfig
		*out = new(WebIdentityTokenConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssumeRoleWithWebIdentityOptions.
func (in *AssumeRoleWithWebIdentityOptions) DeepCopy() *AssumeRoleWithWebIdentityOptions {
	if in == nil {
		return nil
	}
	out := new(AssumeRoleWithWebIdentityOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicURLConfig) DeepCopyInto(out *DynamicURLConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicURLConfig.
func (in *DynamicURLConfig) DeepCopy() *DynamicURLConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicURLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfig) DeepCopyInto(out *EndpointConfig) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HostnameImmutable != nil {
		in, out := &in.HostnameImmutable, &out.HostnameImmutable
		*out = new(bool)
		**out = **in
	}
	if in.PartitionID != nil {
		in, out := &in.PartitionID, &out.PartitionID
		*out = new(string)
		**out = **in
	}
	if in.SigningName != nil {
		in, out := &in.SigningName, &out.SigningName
		*out = new(string)
		**out = **in
	}
	if in.SigningRegion != nil {
		in, out := &in.SigningRegion, &out.SigningRegion
		*out = new(string)
		**out = **in
	}
	if in.SigningMethod != nil {
		in, out := &in.SigningMethod, &out.SigningMethod
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfig.
func (in *EndpointConfig) DeepCopy() *EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfig) DeepCopyInto(out *FunctionConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfig.
func (in *FunctionConfig) DeepCopy() *FunctionConfig {
	if in == nil {
		return nil
	}
	out := new(FunctionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigList) DeepCopyInto(out *FunctionConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FunctionConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigList.
func (in *FunctionConfigList) DeepCopy() *FunctionConfigList {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionConfigSpec) DeepCopyInto(out *FunctionConfigSpec) {
	*out = *in
	if in.ForAWS != nil {
		in, out := &in.ForAWS, &out.ForAWS
		*out = new(AWSFunctionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionConfigSpec.
func (in *FunctionConfigSpec) DeepCopy() *FunctionConfigSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionCredentials) DeepCopyInto(out *FunctionCredentials) {
	*out = *in
	if in.WebIdentity != nil {
		in, out := &in.WebIdentity, &out.WebIdentity
		*out = new(AssumeRoleWithWebIdentityOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Upbound != nil {
		in, out := &in.Upbound, &out.Upbound
		*out = new(Upbound)
		(*in).DeepCopyInto(*out)
	}
	in.CommonCredentialSelectors.DeepCopyInto(&out.CommonCredentialSelectors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionCredentials.
func (in *FunctionCredentials) DeepCopy() *FunctionCredentials {
	if in == nil {
		return nil
	}
	out := new(FunctionCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLConfig) DeepCopyInto(out *URLConfig) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(string)
		**out = **in
	}
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = new(DynamicURLConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLConfig.
func (in *URLConfig) DeepCopy() *URLConfig {
	if in == nil {
		return nil
	}
	out := new(URLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upbound) DeepCopyInto(out *Upbound) {
	*out = *in
	if in.WebIdentity != nil {
		in, out := &in.WebIdentity, &out.WebIdentity
		*out = new(AssumeRoleWithWebIdentityOptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upbound.
func (in *Upbound) DeepCopy() *Upbound {
	if in == nil {
		return nil
	}
	out := new(Upbound)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebIdentityTokenConfig) DeepCopyInto(out *WebIdentityTokenConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Fs != nil {
		in, out := &in.Fs, &out.Fs
		*out = new(v1.FsSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebIdentityTokenConfig.
func (in *WebIdentityTokenConfig) DeepCopy() *WebIdentityTokenConfig {
	if in == nil {
		return nil
	}
	out := new(WebIdentityTokenConfig)
	in.DeepCopyInto(out)
	return out
}
